source 'https://github.com/CocoaPods/Specs'

xcodeproj 'DCClass Tests'
workspace '../DCClass'
inhibit_all_warnings!

platform :ios, '7.0'

pod 'OCMock', '~> 2.1.1'
pod 'Expecta', '~> 0.2.1'
pod 'DCClass', :path => '../'
